### PR TITLE
Wordpress Security Scanner

### PR DESCRIPTION
**Pull request by cyberamt**
This pull request adds the "WP-Scan" module to Artemis. [github.com/wpscanteam/wpscan](https://github.com/wpscanteam/wpscan)

WP-Scan is an open-source WordPress security scanner designed to identify vulnerabilities and security issues within WordPress installations.

Additionally, you can enhance the module's functionality by adding your official WPScan API key to a `WPSCAN_API_KEY` variable in the `ExtraModulesConfig` class. This allows Artemis to also query the official WPScan API.

Please review the changes and let me know if you have any concerns or suggestions for improvement.

### CODE REVIEW

**Comment by cyberamt** [comment]
Hey @kazet what do you think about this tool for Artemis? Anything i can improve on the code or do you think it is not that interesting because you got other wordpress tools?

**Comment by kazet** [comment]
Hello,

getting back to you! We can merge wpscan module but we will need to add some kind of a disclaimer that describes the terms to run wpscan, links to the license etc. - we will propose something next week.

Would it be possible for you to add reporting capabilities to this PR, so that issues found by wpscan are added to the reports generated by Artemis?

**Comment by cyberamt** [comment]
> Would it be possible for you to add reporting capabilities to this PR, so that issues found by wpscan are added to the reports generated by Artemis?

Yes i will work on that and improve the pull request 👍🏻

**Comment by kazet** [comment]
Hello,

made some minor improvements, e.g. improved the report grammar, added license disclaimer and due to wpscan non-standard license made the module disabled by default.

Please make sure the PR is still consistent with your vision and if it still is, let me know - we will merge ;)

Sorry again that it took so long!

**Comment by cyberamt** [comment]
> Please make sure the PR is still consistent with your vision and if it still is, let me know - we will merge ;)

😄 I would love if you merge the branch.

**Pull request merged**
